version: "3.1"

services:
  nginx:
    build: ./docker/nginx
    container_name: YII_NGINX
    restart: always
    volumes:
      - ${APPLICATION_DIR}:/var/www/app
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:${NGINX_HTTP}
      - 127.0.0.1:${NGINX_HTTPS}
    networks:
      - yii-network

  php:
    build: ./docker/php
    restart: always
    container_name: YII_PHP
    volumes:
      - ${APPLICATION_DIR}:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - yii-network

  postgres:
    image: postgres:12.1
    restart: always
    container_name: YII_POSTGRES
    volumes:
      - yii-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${PGSQL_PORT}
    networks:
      - yii-network

networks:
  yii-network:
    driver: bridge

volumes:
  yii-postgres: